#!/bin/sh
SOCKET_DIR=/sockets
CONF=/etc/nginx/runtime/upstream.conf
CONF_TMP=/etc/nginx/runtime/upstream.conf.tmp
INTERVAL=5
INSTANCES="1 2"

probe() {
  sock="$1"
  [ -S "$sock" ] || return 1
  curl -s --max-time 2 --unix-socket "$sock" http://localhost/api/version >/dev/null 2>&1
}

write_conf() {
  healthy=0
  {
    echo "# generated by healthcheck.sh - do not edit"
    echo "upstream ollama_pool {"
    echo "  ip_hash;"
    for i in $INSTANCES; do
      if probe "$SOCKET_DIR/ollama-$i.sock"; then
        echo "  server unix:/sockets/ollama-$i.sock;"
        healthy=$((healthy + 1))
      else
        echo "  # ollama-$i DOWN"
      fi
    done
    if [ "$healthy" -eq 0 ]; then
      # Keep nginx valid while nothing is healthy: a placeholder server that
      # never answers. The watch loop replaces it as soon as an instance
      # passes its /api/version probe.
      echo "  server unix:/sockets/none.sock;"
    fi
    echo "  keepalive 32;"
    echo "}"
  } > "$CONF_TMP"

  if [ ! -f "$CONF" ] || ! cmp -s "$CONF" "$CONF_TMP"; then
    mv "$CONF_TMP" "$CONF"
    return 0
  fi
  rm -f "$CONF_TMP"
  return 1
}

case "$1" in
  --init)
    # Ensure the upstream config exists before nginx starts. write_conf
    # returns 1 when the config is unchanged, so always succeed here.
    write_conf || true
    ;;
  --watch)
    while true; do
      sleep "$INTERVAL"
      if write_conf; then
        nginx -s reload >/dev/null 2>&1
      fi
    done
    ;;
  *)
    echo "usage: $0 --init|--watch" >&2
    exit 1
    ;;
esac
