#!/bin/sh
SOCKET_DIR=/sockets
CONF=/etc/nginx/runtime/upstream.conf
CONF_TMP=/etc/nginx/runtime/upstream.conf.tmp
INTERVAL=5
INSTANCES="1 2 3"

probe() {
  sock="$1"
  [ -S "$sock" ] || return 1
  curl -s --max-time 2 --unix-socket "$sock" http://localhost/api/version >/dev/null 2>&1
}

write_conf() {
  {
    echo "# generated by healthcheck.sh - do not edit"
    echo "upstream ollama_pool {"
    echo "  ip_hash;"
    for i in $INSTANCES; do
      if probe "$SOCKET_DIR/ollama-$i.sock"; then
        echo "  server unix:/sockets/ollama-$i.sock;"
      else
        echo "  # ollama-$i DOWN"
      fi
    done
    echo "  keepalive 32;"
    echo "}"
  } > "$CONF_TMP"

  if [ ! -f "$CONF" ] || ! cmp -s "$CONF" "$CONF_TMP"; then
    mv "$CONF_TMP" "$CONF"
    return 0
  fi
  rm -f "$CONF_TMP"
  return 1
}

case "$1" in
  --init)
    write_conf
    ;;
  --watch)
    while true; do
      sleep "$INTERVAL"
      if write_conf; then
        nginx -s reload >/dev/null 2>&1
      fi
    done
    ;;
  *)
    echo "usage: $0 --init|--watch" >&2
    exit 1
    ;;
esac
